#pragma once

namespace OtaVersion {

// Describes the candidate version relative to the currently running version.
enum class Comparison { Invalid, Older, Equal, Newer };

// The candidate must be a stable three- or four-component version, optionally
// prefixed with "v" (the official repository's release-tag convention). The
// current version may additionally carry a build or RC suffix generated by the
// firmware build. Parsing uses fixed-size stack values and does not allocate.
Comparison compare(const char* currentVersion, const char* candidateVersion);

}  // namespace OtaVersion
